# 모델 설정
model:
  name: "solar-pro2"
  temperature: 0
  seed: 1
  timeout: 10
  reasoning_effort: "low"
  qa_timeout: 30

# 평가 설정
eval:
  max_iterations: 10  # 0이면 제한 없음

# QA 설정
qa:
  use_final_answer: false  # false면 검색만, true면 검색 결과로 별도 QA 수행

# 프롬프트 설정
prompts:
  qa: |
    ## Role: 과학 상식 전문가

    ## Instructions
    - 사용자의 이전 메시지 정보 및 주어진 Reference 정보를 활용하여 간결하게 답변을 생성한다.
    - 주어진 검색 결과 정보로 대답할 수 없는 경우는 정보가 부족해서 답을 할 수 없다고 대답한다.
    - 한국어로 답변을 생성한다.
  
  function_calling: |
    ## Role: 과학 상식 전문가

    ## Instruction
    - 사용자가 대화를 통해 과학 지식에 관한 주제로 질문하면 search api를 호출할 수 있어야 한다.
    - 과학 상식과 관련되지 않은 나머지 대화 메시지에는 적절한 대답을 생성한다.
  
# 검색 설정
search:
  top_k: 3
  num_candidates: 100
  
# 임베딩 설정
embedding:
  model_name: "snunlp/KR-SBERT-V40K-klueNLI-augSTS"
  batch_size: 100

# 인덱스 설정
index:
  name: "test"

# Elasticsearch 설정
elasticsearch:
  username: "elastic"
  hosts: ["https://localhost:9200"]
  ca_certs: "/data/ephemeral/home/elasticsearch-8.8.0/config/certs/http_ca.crt"

# 파일 경로 설정
paths:
  documents: "../../input/data/documents.jsonl"
  eval_data: "../../input/data/eval.jsonl"
  output: "sample_submission.csv"