# 모델 설정
model:
  name: "solar-pro2"
  temperature: 0
  seed: 1
  timeout: 1000
  reasoning_effort: "high"
  qa_timeout: 1000

# 평가 설정
eval:
  max_iterations: 0  # 0이면 제한 없음

# QA 설정
qa:
  use_final_answer: false  # false면 검색만, true면 검색 결과로 별도 QA 수행

# 프롬프트 설정
prompts:
  qa: |
    ## Role: 과학 상식 전문가

    ## Instructions
    - 사용자의 이전 메시지 정보 및 주어진 Reference 정보를 활용하여 간결하게 답변을 생성한다.
    - 주어진 검색 결과 정보로 대답할 수 없는 경우는 정보가 부족해서 답을 할 수 없다고 대답한다.
    - 한국어로 답변을 생성한다.
  
  function_calling: |
    ## Role: 과학 상식 전문가

    ## Instruction
    - 먼저 질문이 chit-chat 즉, 지극히 개인적질문이나 안부, 인사, 감정에 대한 질문 일 경우에는 절대로 search api를 호출하지 말고 적절한 대답을 생성한다.
    - chit-chat 즉, 지극히 개인적질문이나 안부, 인사, 감정에 대한 질문 이외에는 무조건 반드시 search api를 호출해야 하고 스스로 판단해서 대답하면 안된다.
    - 과학 상식 범위 내에서 설명 가능하더라도 반드시 search api를 호출해야 한다.
    - 추가 검색 없이도 과학 상식으로 설명 가능한 범위이더라도 반드시 search api를 호출해야 한다.
    - 어떤 사건에 관한것이거나 코드 프로그램적인 질문을 하더라도 반드시 search api를 호출해야 한다.
    - search api를 호출할 때는 반드시 질문에 대한 최종 korean query를 생성해서 호출해야 한다.

  standalone_query_description: "Final korean query suitable for use in search from the user messages history."
  
# 리트리브 설정
retrieve:
  sparse:
    enabled: true   # sparse retrieve 활성화 여부
    top_k: 30       # sparse_retrieve에서 가져올 문서 수
  dense_upstage:
    enabled: true   # Upstage 임베딩 기반 dense 활성화 여부
    model_name: "solar-embedding-1-large"
    top_k: 30       # dense_retrieve_upstage에서 가져올 문서 수
    num_candidates: 500  # KNN 후보 수
  dense_sbert:
    enabled: true   # SBERT 임베딩 기반 dense 활성화 여부
    model_name: "snunlp/KR-SBERT-V40K-klueNLI-augSTS"
    top_k: 30       # dense_retrieve_sbert에서 가져올 문서 수
    num_candidates: 500  # KNN 후보 수
  dense_upstage_hyde:
    enabled: false  # HyDE 기법을 활용한 Upstage 임베딩 활성화 여부 (dense_upstage와 동일한 모델 사용)
    top_k: 30       # dense_retrieve_upstage_hyde에서 가져올 문서 수
    num_candidates: 500  # KNN 후보 수
    hyde_prompt: "다음 질문에 대해 전문적이고 상세한 설명 문서를 작성해주세요. 과학적 사실과 정확한 정보를 바탕으로 체계적으로 서술하세요."

# 리랭커 설정
reranker:
  model_name: "Qwen/Qwen3-Reranker-8B"
  batch_size: 4
  instruction: "Given a web search query, retrieve relevant passages"
  use_reranker: true
  top_k: 3        # 리랭킹 후 최종 선택할 문서 수
  
# 임베딩 배치 설정 (모델명은 각 retrieve 섹션에 정의)
embedding:
  batch_size: 100

# 인덱스 설정
index:
  name: "test"
  force_recreate: true  # false면 기존 인덱스 재사용, true면 삭제 후 재생성

# Elasticsearch 설정
elasticsearch:
  username: "elastic"
  hosts: ["https://localhost:9200"]
  # ca_certs: "/data/ephemeral/home/elasticsearch-8.8.0/config/certs/http_ca.crt"
  ca_certs: "/data/ephemeral/home/elasticsearch-9.0.3/config/certs/http_ca.crt"

# 파일 경로 설정
paths:
  documents: "../../input/data/documents.jsonl"
  eval_data: "../../input/data/eval.jsonl"
  output: "submission.csv"  # Hydra가 자동으로 outputs/{date}/{time}/ 폴더에 저장
